using System.Printing;

namespace PrintDialogX.Internal
{
    internal class SettingsHelper
    {
        public static OutputColor ConvertPageColor(PrintSettings.PageColor color)
        {
            return (OutputColor)((int)color + 1);
        }

        public static OutputQuality ConvertPageQuality(PrintSettings.PageQuality quality)
        {
            return (OutputQuality)((int)quality + 1);
        }

        public static Duplexing ConvertDoubleSided(PrintSettings.DoubleSided doubleSided)
        {
            return (Duplexing)((int)doubleSided + 1);
        }

        public static PageMediaSize ConvertPageSize(PrintSettings.PageSize size)
        {
            return new PageMediaSize((PageMediaSizeName)((int)size + 1));
        }

        public static PageMediaType ConvertPageType(PrintSettings.PageType type)
        {
            return (PageMediaType)((int)type + 1);
        }

        public static string GetPageSizeName(PageMediaSizeName? size)
        {
            return size switch
            {
                PageMediaSizeName.BusinessCard => "Business Card",
                PageMediaSizeName.CreditCard => "Credit Card",
                PageMediaSizeName.ISOA0 => "A0",
                PageMediaSizeName.ISOA1 => "A1",
                PageMediaSizeName.ISOA10 => "A10",
                PageMediaSizeName.ISOA2 => "A2",
                PageMediaSizeName.ISOA3 => "A3",
                PageMediaSizeName.ISOA3Extra => "A3 Extra",
                PageMediaSizeName.ISOA3Rotated => "A3 Rotated",
                PageMediaSizeName.ISOA4 => "A4",
                PageMediaSizeName.ISOA4Extra => "A4 Extra",
                PageMediaSizeName.ISOA4Rotated => "A4 Rotated",
                PageMediaSizeName.ISOA5 => "A5",
                PageMediaSizeName.ISOA5Extra => "A5 Extra",
                PageMediaSizeName.ISOA5Rotated => "A5 Rotated",
                PageMediaSizeName.ISOA6 => "A6",
                PageMediaSizeName.ISOA6Rotated => "A6 Rotated",
                PageMediaSizeName.ISOA7 => "A7",
                PageMediaSizeName.ISOA8 => "A8",
                PageMediaSizeName.ISOA9 => "A9",
                PageMediaSizeName.ISOB0 => "ISO B0",
                PageMediaSizeName.ISOB1 => "ISO B1",
                PageMediaSizeName.ISOB10 => "ISO B10",
                PageMediaSizeName.ISOB2 => "ISO B2",
                PageMediaSizeName.ISOB3 => "ISO B3",
                PageMediaSizeName.ISOB4 => "ISO B4",
                PageMediaSizeName.ISOB4Envelope => "ISO B4 Envelope",
                PageMediaSizeName.ISOB5Envelope => "ISO B5 Envelope",
                PageMediaSizeName.ISOB5Extra => "ISO B5 Extra",
                PageMediaSizeName.ISOB7 => "ISO B7",
                PageMediaSizeName.ISOB8 => "ISO B8",
                PageMediaSizeName.ISOB9 => "ISO B9",
                PageMediaSizeName.ISOC0 => "C0",
                PageMediaSizeName.ISOC1 => "C1",
                PageMediaSizeName.ISOC2 => "C2",
                PageMediaSizeName.ISOC3 => "C3",
                PageMediaSizeName.ISOC3Envelope => "C3 Envelope",
                PageMediaSizeName.ISOC4 => "C4",
                PageMediaSizeName.ISOC4Envelope => "C4 Envelope",
                PageMediaSizeName.ISOC5 => "C5",
                PageMediaSizeName.ISOC5Envelope => "C5 Envelope",
                PageMediaSizeName.ISOC6 => "C6",
                PageMediaSizeName.ISOC6C5Envelope => "C6C5 Envelope",
                PageMediaSizeName.ISOC6Envelope => "C6 Envelope",
                PageMediaSizeName.ISOC7 => "C7",
                PageMediaSizeName.ISOC8 => "C8",
                PageMediaSizeName.ISOC9 => "C9",
                PageMediaSizeName.ISOC10 => "C10",
                PageMediaSizeName.ISODLEnvelope => "DL Envelope",
                PageMediaSizeName.ISODLEnvelopeRotated => "DL Envelope Rotated",
                PageMediaSizeName.ISOSRA3 => "SRA3",
                PageMediaSizeName.Japan2LPhoto => "2L Photo",
                PageMediaSizeName.JapanChou3Envelope => "Chou 3 Envelope",
                PageMediaSizeName.JapanChou3EnvelopeRotated => "Chou 3 Envelope Rotated",
                PageMediaSizeName.JapanChou4Envelope => "Chou 4 Envelope",
                PageMediaSizeName.JapanChou4EnvelopeRotated => "Chou 4 Envelope Rotated",
                PageMediaSizeName.JapanDoubleHagakiPostcard => "Double Hagaki Postcard",
                PageMediaSizeName.JapanDoubleHagakiPostcardRotated => "Double Hagaki Postcard Rotated",
                PageMediaSizeName.JapanHagakiPostcard => "Hagaki Postcard",
                PageMediaSizeName.JapanHagakiPostcardRotated => "Hagaki Postcard Rotated",
                PageMediaSizeName.JapanKaku2Envelope => "Kaku 2 Envelope",
                PageMediaSizeName.JapanKaku2EnvelopeRotated => "Kaku 2 Envelope Rotated",
                PageMediaSizeName.JapanKaku3Envelope => "Kaku 3 Envelope",
                PageMediaSizeName.JapanKaku3EnvelopeRotated => "Kaku 3 Envelope Rotated",
                PageMediaSizeName.JapanLPhoto => "L Photo",
                PageMediaSizeName.JapanQuadrupleHagakiPostcard => "Quadruple Hagaki Postcard",
                PageMediaSizeName.JapanYou1Envelope => "You 1 Envelope",
                PageMediaSizeName.JapanYou2Envelope => "You 2 Envelope",
                PageMediaSizeName.JapanYou3Envelope => "You 3 Envelope",
                PageMediaSizeName.JapanYou4Envelope => "You 4 Envelope",
                PageMediaSizeName.JapanYou4EnvelopeRotated => "You 4 Envelope Rotated",
                PageMediaSizeName.JapanYou6Envelope => "You 6 Envelope",
                PageMediaSizeName.JapanYou6EnvelopeRotated => "You 6 Envelope Rotated",
                PageMediaSizeName.JISB0 => "JIS B0",
                PageMediaSizeName.JISB1 => "JIS B1",
                PageMediaSizeName.JISB10 => "JIS B10",
                PageMediaSizeName.JISB2 => "JIS B2",
                PageMediaSizeName.JISB3 => "JIS B3",
                PageMediaSizeName.JISB4 => "JIS B4",
                PageMediaSizeName.JISB4Rotated => "JIS B4 Rotated",
                PageMediaSizeName.JISB5 => "JIS B5",
                PageMediaSizeName.JISB5Rotated => "JIS B5 Rotated",
                PageMediaSizeName.JISB6 => "JIS B6",
                PageMediaSizeName.JISB6Rotated => "JIS B6 Rotated",
                PageMediaSizeName.JISB7 => "JIS B7",
                PageMediaSizeName.JISB8 => "JIS B8",
                PageMediaSizeName.JISB9 => "JIS B9",
                PageMediaSizeName.NorthAmerica10x11 => "10 × 11 in",
                PageMediaSizeName.NorthAmerica10x12 => "10 × 12 in",
                PageMediaSizeName.NorthAmerica10x14 => "10 × 14 in",
                PageMediaSizeName.NorthAmerica11x17 => "11 × 17 in",
                PageMediaSizeName.NorthAmerica14x17 => "14 × 17 in",
                PageMediaSizeName.NorthAmerica4x6 => "4 × 6 in",
                PageMediaSizeName.NorthAmerica4x8 => "4 × 8 in",
                PageMediaSizeName.NorthAmerica5x7 => "5 × 7 in",
                PageMediaSizeName.NorthAmerica8x10 => "8 × 10 in",
                PageMediaSizeName.NorthAmerica9x11 => "9 × 11 in",
                PageMediaSizeName.NorthAmericaArchitectureASheet => "Architecture A Sheet",
                PageMediaSizeName.NorthAmericaArchitectureBSheet => "Architecture B Sheet",
                PageMediaSizeName.NorthAmericaArchitectureCSheet => "Architecture C Sheet",
                PageMediaSizeName.NorthAmericaArchitectureDSheet => "Architecture D Sheet",
                PageMediaSizeName.NorthAmericaArchitectureESheet => "Architecture E Sheet",
                PageMediaSizeName.NorthAmericaCSheet => "C Sheet",
                PageMediaSizeName.NorthAmericaDSheet => "D Sheet",
                PageMediaSizeName.NorthAmericaESheet => "E Sheet",
                PageMediaSizeName.NorthAmericaExecutive => "Executive",
                PageMediaSizeName.NorthAmericaGermanLegalFanfold => "German Legal Fanfold",
                PageMediaSizeName.NorthAmericaGermanStandardFanfold => "German Standard Fanfold",
                PageMediaSizeName.NorthAmericaLegal => "Legal",
                PageMediaSizeName.NorthAmericaLegalExtra => "Legal Extra",
                PageMediaSizeName.NorthAmericaLetter => "Letter",
                PageMediaSizeName.NorthAmericaLetterExtra => "Letter Extra",
                PageMediaSizeName.NorthAmericaLetterPlus => "Letter Plus",
                PageMediaSizeName.NorthAmericaLetterRotated => "Letter Rotated",
                PageMediaSizeName.NorthAmericaMonarchEnvelope => "Monarch Envelope",
                PageMediaSizeName.NorthAmericaNote => "Note",
                PageMediaSizeName.NorthAmericaNumber10Envelope => "Number 10 Envelope",
                PageMediaSizeName.NorthAmericaNumber10EnvelopeRotated => "Number 10 Envelope Rotated",
                PageMediaSizeName.NorthAmericaNumber11Envelope => "Number 11 Envelope",
                PageMediaSizeName.NorthAmericaNumber12Envelope => "Number 12 Envelope",
                PageMediaSizeName.NorthAmericaNumber14Envelope => "Number 14 Envelope",
                PageMediaSizeName.NorthAmericaNumber9Envelope => "Number 9 Envelope",
                PageMediaSizeName.NorthAmericaPersonalEnvelope => "Personal Envelope",
                PageMediaSizeName.NorthAmericaQuarto => "Quarto",
                PageMediaSizeName.NorthAmericaStatement => "Statement",
                PageMediaSizeName.NorthAmericaSuperA => "Super A",
                PageMediaSizeName.NorthAmericaSuperB => "Super B",
                PageMediaSizeName.NorthAmericaTabloid => "Tabloid",
                PageMediaSizeName.NorthAmericaTabloidExtra => "Tabloid Extra",
                PageMediaSizeName.OtherMetricA3Plus => "A3 Plus",
                PageMediaSizeName.OtherMetricA4Plus => "A4 Plus",
                PageMediaSizeName.OtherMetricFolio => "Folio",
                PageMediaSizeName.OtherMetricInviteEnvelope => "Invite Envelope",
                PageMediaSizeName.OtherMetricItalianEnvelope => "Italian Envelope",
                PageMediaSizeName.PRC10Envelope => "#10 Envelope",
                PageMediaSizeName.PRC10EnvelopeRotated => "#10 Envelope Rotated",
                PageMediaSizeName.PRC16K => "16K",
                PageMediaSizeName.PRC16KRotated => "16K Rotated",
                PageMediaSizeName.PRC1Envelope => "#1 Envelope",
                PageMediaSizeName.PRC1EnvelopeRotated => "#1 Envelope Rotated",
                PageMediaSizeName.PRC2Envelope => "#2 Envelope",
                PageMediaSizeName.PRC2EnvelopeRotated => "#2 Envelope Rotated",
                PageMediaSizeName.PRC32K => "32K",
                PageMediaSizeName.PRC32KBig => "32K Big",
                PageMediaSizeName.PRC32KRotated => "32K Rotated",
                PageMediaSizeName.PRC3Envelope => "#3 Envelope",
                PageMediaSizeName.PRC3EnvelopeRotated => "#3 Envelope Rotated",
                PageMediaSizeName.PRC4Envelope => "#4 Envelope",
                PageMediaSizeName.PRC4EnvelopeRotated => "#4 Envelope Rotated",
                PageMediaSizeName.PRC5Envelope => "#5 Envelope",
                PageMediaSizeName.PRC5EnvelopeRotated => "#5 Envelope Rotated",
                PageMediaSizeName.PRC6Envelope => "#6 Envelope",
                PageMediaSizeName.PRC6EnvelopeRotated => "#6 Envelope Rotated",
                PageMediaSizeName.PRC7Envelope => "#7 Envelope",
                PageMediaSizeName.PRC7EnvelopeRotated => "#7 Envelope Rotated",
                PageMediaSizeName.PRC8Envelope => "#8 Envelope",
                PageMediaSizeName.PRC8EnvelopeRotated => "#8 Envelope Rotated",
                PageMediaSizeName.PRC9Envelope => "#9 Envelope",
                PageMediaSizeName.PRC9EnvelopeRotated => "#9 Envelope Rotated",
                PageMediaSizeName.Roll04Inch => "4-inch Wide Roll",
                PageMediaSizeName.Roll06Inch => "6-inch Wide Roll",
                PageMediaSizeName.Roll08Inch => "8-inch Wide Roll",
                PageMediaSizeName.Roll12Inch => "12-inch Wide Roll",
                PageMediaSizeName.Roll15Inch => "15-inch Wide Roll",
                PageMediaSizeName.Roll18Inch => "18-inch Wide Roll",
                PageMediaSizeName.Roll22Inch => "22-inch Wide Roll",
                PageMediaSizeName.Roll24Inch => "24-inch Wide Roll",
                PageMediaSizeName.Roll30Inch => "30-inch Wide Roll",
                PageMediaSizeName.Roll36Inch => "36-inch Wide Roll",
                PageMediaSizeName.Roll54Inch => "54-inch Wide Roll",
                _ => "Custom Size"
            };
        }

        public static string GetPageSizeName(PrintSettings.PageSize size)
        {
            return GetPageSizeName(ConvertPageSize(size).PageMediaSizeName);
        }

        public static string GetPageTypeName(PageMediaType type)
        {
            return type switch
            {
                PageMediaType.Archival => "Archival",
                PageMediaType.AutoSelect => "Auto Select",
                PageMediaType.BackPrintFilm => "Back Print Film",
                PageMediaType.Bond => "Bond",
                PageMediaType.CardStock => "Card Stock",
                PageMediaType.Continuous => "Continuous",
                PageMediaType.EnvelopePlain => "Envelope Plain",
                PageMediaType.EnvelopeWindow => "Envelope Window",
                PageMediaType.Fabric => "Fabric",
                PageMediaType.HighResolution => "High Resolution",
                PageMediaType.Label => "Label",
                PageMediaType.MultiLayerForm => "Multi Layer Form",
                PageMediaType.MultiPartForm => "Multi Part Form",
                PageMediaType.Photographic => "Photographic",
                PageMediaType.PhotographicFilm => "Photographic Film",
                PageMediaType.PhotographicGlossy => "Photographic Glossy",
                PageMediaType.PhotographicHighGloss => "Photographic High Gloss",
                PageMediaType.PhotographicMatte => "Photographic Matte",
                PageMediaType.PhotographicSatin => "Photographic Satin",
                PageMediaType.PhotographicSemiGloss => "Photographic Semi Gloss",
                PageMediaType.Plain => "Plain",
                PageMediaType.Screen => "Screen",
                PageMediaType.ScreenPaged => "Screen Paged",
                PageMediaType.Stationery => "Stationery",
                PageMediaType.TabStockFull => "Tab Stock Full",
                PageMediaType.TabStockPreCut => "Tab Stock Pre Cut",
                PageMediaType.Transparency => "Transparency",
                PageMediaType.TShirtTransfer => "T-shirt Transfer",
                _ => "Unknown Type"
            };
        }

        public static string GetPageTypeName(PrintSettings.PageType type)
        {
            return GetPageTypeName(ConvertPageType(type));
        }

        public static string GetInputBinName(InputBin inputBin)
        {
            return inputBin switch
            {
                InputBin.AutoSelect => "Auto Select",
                InputBin.AutoSheetFeeder => "Auto Sheet Feeder",
                InputBin.Cassette => "Cassette",
                InputBin.Manual => "Manual",
                InputBin.Tractor => "Tractor",
                _ => "Unknown Input Bin"
            };
        }

        public static PageMediaSizeName GetPageSizeName(string size)
        {
            string sizeAdjusted = (size.StartsWith("psk:") ? size.Remove(0, 4) : size).ToLower();
            return sizeAdjusted switch
            {
                "businesscard" => PageMediaSizeName.BusinessCard,
                "creditcard" => PageMediaSizeName.CreditCard,
                "isoa0" => PageMediaSizeName.ISOA0,
                "isoa1" => PageMediaSizeName.ISOA1,
                "isoa10" => PageMediaSizeName.ISOA10,
                "isoa2" => PageMediaSizeName.ISOA2,
                "isoa3" => PageMediaSizeName.ISOA3,
                "isoa3extra" => PageMediaSizeName.ISOA3Extra,
                "isoa3rotated" => PageMediaSizeName.ISOA3Rotated,
                "isoa4" => PageMediaSizeName.ISOA4,
                "isoa4extra" => PageMediaSizeName.ISOA4Extra,
                "isoa4rotated" => PageMediaSizeName.ISOA4Rotated,
                "isoa5" => PageMediaSizeName.ISOA5,
                "isoa5extra" => PageMediaSizeName.ISOA5Extra,
                "isoa5rotated" => PageMediaSizeName.ISOA5Rotated,
                "isoa6" => PageMediaSizeName.ISOA6,
                "isoa6rotated" => PageMediaSizeName.ISOA6Rotated,
                "isoa7" => PageMediaSizeName.ISOA7,
                "isoa8" => PageMediaSizeName.ISOA8,
                "isoa9" => PageMediaSizeName.ISOA9,
                "isob0" => PageMediaSizeName.ISOB0,
                "isob1" => PageMediaSizeName.ISOB1,
                "isob10" => PageMediaSizeName.ISOB10,
                "isob2" => PageMediaSizeName.ISOB2,
                "isob3" => PageMediaSizeName.ISOB3,
                "isob4" => PageMediaSizeName.ISOB4,
                "isob4envelope" => PageMediaSizeName.ISOB4Envelope,
                "isob5envelope" => PageMediaSizeName.ISOB5Envelope,
                "isob5extra" => PageMediaSizeName.ISOB5Extra,
                "isob7" => PageMediaSizeName.ISOB7,
                "isob8" => PageMediaSizeName.ISOB8,
                "isob9" => PageMediaSizeName.ISOB9,
                "isoc0" => PageMediaSizeName.ISOC0,
                "isoc1" => PageMediaSizeName.ISOC1,
                "isoc2" => PageMediaSizeName.ISOC2,
                "isoc3" => PageMediaSizeName.ISOC3,
                "isoc3envelope" => PageMediaSizeName.ISOC3Envelope,
                "isoc4" => PageMediaSizeName.ISOC4,
                "isoc4envelope" => PageMediaSizeName.ISOC4Envelope,
                "isoc5" => PageMediaSizeName.ISOC5,
                "isoc5envelope" => PageMediaSizeName.ISOC5Envelope,
                "isoc6" => PageMediaSizeName.ISOC6,
                "isoc6c5envelope" => PageMediaSizeName.ISOC6C5Envelope,
                "isoc6envelope" => PageMediaSizeName.ISOC6Envelope,
                "isoc7" => PageMediaSizeName.ISOC7,
                "isoc8" => PageMediaSizeName.ISOC8,
                "isoc9" => PageMediaSizeName.ISOC9,
                "isoc10" => PageMediaSizeName.ISOC10,
                "isodlenvelope" => PageMediaSizeName.ISODLEnvelope,
                "isodlenveloperotated" => PageMediaSizeName.ISODLEnvelopeRotated,
                "isosra3" => PageMediaSizeName.ISOSRA3,
                "japan2lphoto" => PageMediaSizeName.Japan2LPhoto,
                "japanchou3envelope" => PageMediaSizeName.JapanChou3Envelope,
                "japanchou3enveloperotated" => PageMediaSizeName.JapanChou3EnvelopeRotated,
                "japanchou4envelope" => PageMediaSizeName.JapanChou4Envelope,
                "japanchou4enveloperotated" => PageMediaSizeName.JapanChou4EnvelopeRotated,
                "japandoublehagakipostcard" => PageMediaSizeName.JapanDoubleHagakiPostcard,
                "japandoublehagakipostcardrotated" => PageMediaSizeName.JapanDoubleHagakiPostcardRotated,
                "japanhagakipostcard" => PageMediaSizeName.JapanHagakiPostcard,
                "japanhagakipostcardrotated" => PageMediaSizeName.JapanHagakiPostcardRotated,
                "japankaku2envelope" => PageMediaSizeName.JapanKaku2Envelope,
                "japankaku2enveloperotated" => PageMediaSizeName.JapanKaku2EnvelopeRotated,
                "japankaku3envelope" => PageMediaSizeName.JapanKaku3Envelope,
                "japankaku3enveloperotated" => PageMediaSizeName.JapanKaku3EnvelopeRotated,
                "japanlphoto" => PageMediaSizeName.JapanLPhoto,
                "japanquadruplehagakipostcard" => PageMediaSizeName.JapanQuadrupleHagakiPostcard,
                "japanyou1envelope" => PageMediaSizeName.JapanYou1Envelope,
                "japanyou2envelope" => PageMediaSizeName.JapanYou2Envelope,
                "japanyou3envelope" => PageMediaSizeName.JapanYou3Envelope,
                "japanyou4envelope" => PageMediaSizeName.JapanYou4Envelope,
                "japanyou4enveloperotated" => PageMediaSizeName.JapanYou4EnvelopeRotated,
                "japanyou6envelope" => PageMediaSizeName.JapanYou6Envelope,
                "japanyou6enveloperotated" => PageMediaSizeName.JapanYou6EnvelopeRotated,
                "jisb0" => PageMediaSizeName.JISB0,
                "jisb1" => PageMediaSizeName.JISB1,
                "jisb10" => PageMediaSizeName.JISB10,
                "jisb2" => PageMediaSizeName.JISB2,
                "jisb3" => PageMediaSizeName.JISB3,
                "jisb4" => PageMediaSizeName.JISB4,
                "jisb4rotated" => PageMediaSizeName.JISB4Rotated,
                "jisb5" => PageMediaSizeName.JISB5,
                "jisb5rotated" => PageMediaSizeName.JISB5Rotated,
                "jisb6" => PageMediaSizeName.JISB6,
                "jisb6rotated" => PageMediaSizeName.JISB6Rotated,
                "jisb7" => PageMediaSizeName.JISB7,
                "jisb8" => PageMediaSizeName.JISB8,
                "jisb9" => PageMediaSizeName.JISB9,
                "northamerica10x11" => PageMediaSizeName.NorthAmerica10x11,
                "northamerica10x12" => PageMediaSizeName.NorthAmerica10x12,
                "northamerica10x14" => PageMediaSizeName.NorthAmerica10x14,
                "northamerica11x17" => PageMediaSizeName.NorthAmerica11x17,
                "northamerica14x17" => PageMediaSizeName.NorthAmerica14x17,
                "northamerica4x6" => PageMediaSizeName.NorthAmerica4x6,
                "northamerica4x8" => PageMediaSizeName.NorthAmerica4x8,
                "northamerica5x7" => PageMediaSizeName.NorthAmerica5x7,
                "northamerica8x10" => PageMediaSizeName.NorthAmerica8x10,
                "northamerica9x11" => PageMediaSizeName.NorthAmerica9x11,
                "northamericaarchitectureasheet" => PageMediaSizeName.NorthAmericaArchitectureASheet,
                "northamericaarchitecturebsheet" => PageMediaSizeName.NorthAmericaArchitectureBSheet,
                "northamericaarchitecturecsheet" => PageMediaSizeName.NorthAmericaArchitectureCSheet,
                "northamericaarchitecturedsheet" => PageMediaSizeName.NorthAmericaArchitectureDSheet,
                "northamericaarchitectureesheet" => PageMediaSizeName.NorthAmericaArchitectureESheet,
                "northamericacsheet" => PageMediaSizeName.NorthAmericaCSheet,
                "northamericadsheet" => PageMediaSizeName.NorthAmericaDSheet,
                "northamericaesheet" => PageMediaSizeName.NorthAmericaESheet,
                "northamericaexecutive" => PageMediaSizeName.NorthAmericaExecutive,
                "northamericagermanlegalfanfold" => PageMediaSizeName.NorthAmericaGermanLegalFanfold,
                "northamericagermanstandardfanfold" => PageMediaSizeName.NorthAmericaGermanStandardFanfold,
                "northamericalegal" => PageMediaSizeName.NorthAmericaLegal,
                "northamericalegalextra" => PageMediaSizeName.NorthAmericaLegalExtra,
                "northamericaletter" => PageMediaSizeName.NorthAmericaLetter,
                "northamericaletterextra" => PageMediaSizeName.NorthAmericaLetterExtra,
                "northamericaletterplus" => PageMediaSizeName.NorthAmericaLetterPlus,
                "northamericaletterrotated" => PageMediaSizeName.NorthAmericaLetterRotated,
                "northamericamonarchenvelope" => PageMediaSizeName.NorthAmericaMonarchEnvelope,
                "northamericanote" => PageMediaSizeName.NorthAmericaNote,
                "northamericanumber10envelope" => PageMediaSizeName.NorthAmericaNumber10Envelope,
                "northamericanumber10enveloperotated" => PageMediaSizeName.NorthAmericaNumber10EnvelopeRotated,
                "northamericanumber11envelope" => PageMediaSizeName.NorthAmericaNumber11Envelope,
                "northamericanumber12envelope" => PageMediaSizeName.NorthAmericaNumber12Envelope,
                "northamericanumber14envelope" => PageMediaSizeName.NorthAmericaNumber14Envelope,
                "northamericanumber9envelope" => PageMediaSizeName.NorthAmericaNumber9Envelope,
                "northamericapersonalenvelope" => PageMediaSizeName.NorthAmericaPersonalEnvelope,
                "northamericaquarto" => PageMediaSizeName.NorthAmericaQuarto,
                "northamericastatement" => PageMediaSizeName.NorthAmericaStatement,
                "northamericasupera" => PageMediaSizeName.NorthAmericaSuperA,
                "northamericasuperb" => PageMediaSizeName.NorthAmericaSuperB,
                "northamericatabloid" => PageMediaSizeName.NorthAmericaTabloid,
                "northamericatabloidextra" => PageMediaSizeName.NorthAmericaTabloidExtra,
                "othermetrica3plus" => PageMediaSizeName.OtherMetricA3Plus,
                "othermetrica4plus" => PageMediaSizeName.OtherMetricA4Plus,
                "othermetricfolio" => PageMediaSizeName.OtherMetricFolio,
                "othermetricinviteenvelope" => PageMediaSizeName.OtherMetricInviteEnvelope,
                "othermetricitalianenvelope" => PageMediaSizeName.OtherMetricItalianEnvelope,
                "prc10envelope" => PageMediaSizeName.PRC10Envelope,
                "prc10enveloperotated" => PageMediaSizeName.PRC10EnvelopeRotated,
                "prc16k" => PageMediaSizeName.PRC16K,
                "prc16krotated" => PageMediaSizeName.PRC16KRotated,
                "prc1envelope" => PageMediaSizeName.PRC1Envelope,
                "prc1enveloperotated" => PageMediaSizeName.PRC1EnvelopeRotated,
                "prc2envelope" => PageMediaSizeName.PRC2Envelope,
                "prc2enveloperotated" => PageMediaSizeName.PRC2EnvelopeRotated,
                "prc32k" => PageMediaSizeName.PRC32K,
                "prc32kbig" => PageMediaSizeName.PRC32KBig,
                "prc32krotated" => PageMediaSizeName.PRC32KRotated,
                "prc3envelope" => PageMediaSizeName.PRC3Envelope,
                "prc3enveloperotated" => PageMediaSizeName.PRC3EnvelopeRotated,
                "prc4envelope" => PageMediaSizeName.PRC4Envelope,
                "prc4enveloperotated" => PageMediaSizeName.PRC4EnvelopeRotated,
                "prc5envelope" => PageMediaSizeName.PRC5Envelope,
                "prc5enveloperotated" => PageMediaSizeName.PRC5EnvelopeRotated,
                "prc6envelope" => PageMediaSizeName.PRC6Envelope,
                "prc6enveloperotated" => PageMediaSizeName.PRC6EnvelopeRotated,
                "prc7envelope" => PageMediaSizeName.PRC7Envelope,
                "prc7enveloperotated" => PageMediaSizeName.PRC7EnvelopeRotated,
                "prc8envelope" => PageMediaSizeName.PRC8Envelope,
                "prc8enveloperotated" => PageMediaSizeName.PRC8EnvelopeRotated,
                "prc9envelope" => PageMediaSizeName.PRC9Envelope,
                "prc9enveloperotated" => PageMediaSizeName.PRC9EnvelopeRotated,
                "roll04inch" => PageMediaSizeName.Roll04Inch,
                "roll06inch" => PageMediaSizeName.Roll06Inch,
                "roll08inch" => PageMediaSizeName.Roll08Inch,
                "roll12inch" => PageMediaSizeName.Roll12Inch,
                "roll15inch" => PageMediaSizeName.Roll15Inch,
                "roll18inch" => PageMediaSizeName.Roll18Inch,
                "roll22inch" => PageMediaSizeName.Roll22Inch,
                "roll24inch" => PageMediaSizeName.Roll24Inch,
                "roll30inch" => PageMediaSizeName.Roll30Inch,
                "roll36inch" => PageMediaSizeName.Roll36Inch,
                "roll54inch" => PageMediaSizeName.Roll54Inch,
                _ => PageMediaSizeName.Unknown
            };
        }
    }
}