using System.Linq;
using System.Printing;
using System.Collections.Generic;

namespace PrintDialogX
{
    internal class ValueMappings
    {
        public static T2? Map<T1, T2>(T1? key, Dictionary<T1, T2> mapping) where T1 : notnull where T2 : struct
        {
            return key != null && mapping.TryGetValue(key, out T2 value) ? value : null;
        }

        public static T1 Map<T1, T2>(T2? value, Dictionary<T1, T2> mapping) where T1 : notnull where T2 : struct
        {
            return mapping.First(x => Equals(x.Value, value ?? default)).Key;
        }

        public static readonly Dictionary<Collation, Enums.Collation> CollationMapping = new()
        {
            [Collation.Collated] = Enums.Collation.Collated,
            [Collation.Uncollated] = Enums.Collation.Uncollated
        };

        public static readonly Dictionary<PageOrientation, Enums.Layout> LayoutMapping = new()
        {
            [PageOrientation.Portrait] = Enums.Layout.Portrait,
            [PageOrientation.Landscape] = Enums.Layout.Landscape
        };

        public static readonly Dictionary<PageMediaSizeName, Enums.Size.DefinedSize> SizeNameMapping = new()
        {
            [PageMediaSizeName.ISOA0] = Enums.Size.DefinedSize.ISOA0,
            [PageMediaSizeName.ISOA1] = Enums.Size.DefinedSize.ISOA1,
            [PageMediaSizeName.ISOA10] = Enums.Size.DefinedSize.ISOA10,
            [PageMediaSizeName.ISOA2] = Enums.Size.DefinedSize.ISOA2,
            [PageMediaSizeName.ISOA3] = Enums.Size.DefinedSize.ISOA3,
            [PageMediaSizeName.ISOA3Rotated] = Enums.Size.DefinedSize.ISOA3Rotated,
            [PageMediaSizeName.ISOA3Extra] = Enums.Size.DefinedSize.ISOA3Extra,
            [PageMediaSizeName.ISOA4] = Enums.Size.DefinedSize.ISOA4,
            [PageMediaSizeName.ISOA4Rotated] = Enums.Size.DefinedSize.ISOA4Rotated,
            [PageMediaSizeName.ISOA4Extra] = Enums.Size.DefinedSize.ISOA4Extra,
            [PageMediaSizeName.ISOA5] = Enums.Size.DefinedSize.ISOA5,
            [PageMediaSizeName.ISOA5Rotated] = Enums.Size.DefinedSize.ISOA5Rotated,
            [PageMediaSizeName.ISOA5Extra] = Enums.Size.DefinedSize.ISOA5Extra,
            [PageMediaSizeName.ISOA6] = Enums.Size.DefinedSize.ISOA6,
            [PageMediaSizeName.ISOA6Rotated] = Enums.Size.DefinedSize.ISOA6Rotated,
            [PageMediaSizeName.ISOA7] = Enums.Size.DefinedSize.ISOA7,
            [PageMediaSizeName.ISOA8] = Enums.Size.DefinedSize.ISOA8,
            [PageMediaSizeName.ISOA9] = Enums.Size.DefinedSize.ISOA9,
            [PageMediaSizeName.ISOB0] = Enums.Size.DefinedSize.ISOB0,
            [PageMediaSizeName.ISOB1] = Enums.Size.DefinedSize.ISOB1,
            [PageMediaSizeName.ISOB10] = Enums.Size.DefinedSize.ISOB10,
            [PageMediaSizeName.ISOB2] = Enums.Size.DefinedSize.ISOB2,
            [PageMediaSizeName.ISOB3] = Enums.Size.DefinedSize.ISOB3,
            [PageMediaSizeName.ISOB4] = Enums.Size.DefinedSize.ISOB4,
            [PageMediaSizeName.ISOB4Envelope] = Enums.Size.DefinedSize.ISOB4Envelope,
            [PageMediaSizeName.ISOB5Envelope] = Enums.Size.DefinedSize.ISOB5Envelope,
            [PageMediaSizeName.ISOB5Extra] = Enums.Size.DefinedSize.ISOB5Extra,
            [PageMediaSizeName.ISOB7] = Enums.Size.DefinedSize.ISOB7,
            [PageMediaSizeName.ISOB8] = Enums.Size.DefinedSize.ISOB8,
            [PageMediaSizeName.ISOB9] = Enums.Size.DefinedSize.ISOB9,
            [PageMediaSizeName.ISOC0] = Enums.Size.DefinedSize.ISOC0,
            [PageMediaSizeName.ISOC1] = Enums.Size.DefinedSize.ISOC1,
            [PageMediaSizeName.ISOC10] = Enums.Size.DefinedSize.ISOC10,
            [PageMediaSizeName.ISOC2] = Enums.Size.DefinedSize.ISOC2,
            [PageMediaSizeName.ISOC3] = Enums.Size.DefinedSize.ISOC3,
            [PageMediaSizeName.ISOC3Envelope] = Enums.Size.DefinedSize.ISOC3Envelope,
            [PageMediaSizeName.ISOC4] = Enums.Size.DefinedSize.ISOC4,
            [PageMediaSizeName.ISOC4Envelope] = Enums.Size.DefinedSize.ISOC4Envelope,
            [PageMediaSizeName.ISOC5] = Enums.Size.DefinedSize.ISOC5,
            [PageMediaSizeName.ISOC5Envelope] = Enums.Size.DefinedSize.ISOC5Envelope,
            [PageMediaSizeName.ISOC6] = Enums.Size.DefinedSize.ISOC6,
            [PageMediaSizeName.ISOC6Envelope] = Enums.Size.DefinedSize.ISOC6Envelope,
            [PageMediaSizeName.ISOC6C5Envelope] = Enums.Size.DefinedSize.ISOC6C5Envelope,
            [PageMediaSizeName.ISOC7] = Enums.Size.DefinedSize.ISOC7,
            [PageMediaSizeName.ISOC8] = Enums.Size.DefinedSize.ISOC8,
            [PageMediaSizeName.ISOC9] = Enums.Size.DefinedSize.ISOC9,
            [PageMediaSizeName.ISODLEnvelope] = Enums.Size.DefinedSize.ISODLEnvelope,
            [PageMediaSizeName.ISODLEnvelopeRotated] = Enums.Size.DefinedSize.ISODLEnvelopeRotated,
            [PageMediaSizeName.ISOSRA3] = Enums.Size.DefinedSize.ISOSRA3,
            [PageMediaSizeName.JapanQuadrupleHagakiPostcard] = Enums.Size.DefinedSize.JapanQuadrupleHagakiPostcard,
            [PageMediaSizeName.JISB0] = Enums.Size.DefinedSize.JISB0,
            [PageMediaSizeName.JISB1] = Enums.Size.DefinedSize.JISB1,
            [PageMediaSizeName.JISB10] = Enums.Size.DefinedSize.JISB10,
            [PageMediaSizeName.JISB2] = Enums.Size.DefinedSize.JISB2,
            [PageMediaSizeName.JISB3] = Enums.Size.DefinedSize.JISB3,
            [PageMediaSizeName.JISB4] = Enums.Size.DefinedSize.JISB4,
            [PageMediaSizeName.JISB4Rotated] = Enums.Size.DefinedSize.JISB4Rotated,
            [PageMediaSizeName.JISB5] = Enums.Size.DefinedSize.JISB5,
            [PageMediaSizeName.JISB5Rotated] = Enums.Size.DefinedSize.JISB5Rotated,
            [PageMediaSizeName.JISB6] = Enums.Size.DefinedSize.JISB6,
            [PageMediaSizeName.JISB6Rotated] = Enums.Size.DefinedSize.JISB6Rotated,
            [PageMediaSizeName.JISB7] = Enums.Size.DefinedSize.JISB7,
            [PageMediaSizeName.JISB8] = Enums.Size.DefinedSize.JISB8,
            [PageMediaSizeName.JISB9] = Enums.Size.DefinedSize.JISB9,
            [PageMediaSizeName.JapanChou3Envelope] = Enums.Size.DefinedSize.JapanChou3Envelope,
            [PageMediaSizeName.JapanChou3EnvelopeRotated] = Enums.Size.DefinedSize.JapanChou3EnvelopeRotated,
            [PageMediaSizeName.JapanChou4Envelope] = Enums.Size.DefinedSize.JapanChou4Envelope,
            [PageMediaSizeName.JapanChou4EnvelopeRotated] = Enums.Size.DefinedSize.JapanChou4EnvelopeRotated,
            [PageMediaSizeName.JapanHagakiPostcard] = Enums.Size.DefinedSize.JapanHagakiPostcard,
            [PageMediaSizeName.JapanHagakiPostcardRotated] = Enums.Size.DefinedSize.JapanHagakiPostcardRotated,
            [PageMediaSizeName.JapanKaku2Envelope] = Enums.Size.DefinedSize.JapanKaku2Envelope,
            [PageMediaSizeName.JapanKaku2EnvelopeRotated] = Enums.Size.DefinedSize.JapanKaku2EnvelopeRotated,
            [PageMediaSizeName.JapanKaku3Envelope] = Enums.Size.DefinedSize.JapanKaku3Envelope,
            [PageMediaSizeName.JapanKaku3EnvelopeRotated] = Enums.Size.DefinedSize.JapanKaku3EnvelopeRotated,
            [PageMediaSizeName.JapanYou4Envelope] = Enums.Size.DefinedSize.JapanYou4Envelope,
            [PageMediaSizeName.NorthAmerica10x11] = Enums.Size.DefinedSize.NorthAmerica10x11,
            [PageMediaSizeName.NorthAmerica10x14] = Enums.Size.DefinedSize.NorthAmerica10x14,
            [PageMediaSizeName.NorthAmerica11x17] = Enums.Size.DefinedSize.NorthAmerica11x17,
            [PageMediaSizeName.NorthAmerica9x11] = Enums.Size.DefinedSize.NorthAmerica9x11,
            [PageMediaSizeName.NorthAmericaArchitectureASheet] = Enums.Size.DefinedSize.NorthAmericaArchitectureASheet,
            [PageMediaSizeName.NorthAmericaArchitectureBSheet] = Enums.Size.DefinedSize.NorthAmericaArchitectureBSheet,
            [PageMediaSizeName.NorthAmericaArchitectureCSheet] = Enums.Size.DefinedSize.NorthAmericaArchitectureCSheet,
            [PageMediaSizeName.NorthAmericaArchitectureDSheet] = Enums.Size.DefinedSize.NorthAmericaArchitectureDSheet,
            [PageMediaSizeName.NorthAmericaArchitectureESheet] = Enums.Size.DefinedSize.NorthAmericaArchitectureESheet,
            [PageMediaSizeName.NorthAmericaCSheet] = Enums.Size.DefinedSize.NorthAmericaCSheet,
            [PageMediaSizeName.NorthAmericaDSheet] = Enums.Size.DefinedSize.NorthAmericaDSheet,
            [PageMediaSizeName.NorthAmericaESheet] = Enums.Size.DefinedSize.NorthAmericaESheet,
            [PageMediaSizeName.NorthAmericaExecutive] = Enums.Size.DefinedSize.NorthAmericaExecutive,
            [PageMediaSizeName.NorthAmericaGermanLegalFanfold] = Enums.Size.DefinedSize.NorthAmericaGermanLegalFanfold,
            [PageMediaSizeName.NorthAmericaGermanStandardFanfold] = Enums.Size.DefinedSize.NorthAmericaGermanStandardFanfold,
            [PageMediaSizeName.NorthAmericaLegal] = Enums.Size.DefinedSize.NorthAmericaLegal,
            [PageMediaSizeName.NorthAmericaLegalExtra] = Enums.Size.DefinedSize.NorthAmericaLegalExtra,
            [PageMediaSizeName.NorthAmericaLetter] = Enums.Size.DefinedSize.NorthAmericaLetter,
            [PageMediaSizeName.NorthAmericaLetterRotated] = Enums.Size.DefinedSize.NorthAmericaLetterRotated,
            [PageMediaSizeName.NorthAmericaLetterExtra] = Enums.Size.DefinedSize.NorthAmericaLetterExtra,
            [PageMediaSizeName.NorthAmericaLetterPlus] = Enums.Size.DefinedSize.NorthAmericaLetterPlus,
            [PageMediaSizeName.NorthAmericaMonarchEnvelope] = Enums.Size.DefinedSize.NorthAmericaMonarchEnvelope,
            [PageMediaSizeName.NorthAmericaNote] = Enums.Size.DefinedSize.NorthAmericaNote,
            [PageMediaSizeName.NorthAmericaNumber10Envelope] = Enums.Size.DefinedSize.NorthAmericaNumber10Envelope,
            [PageMediaSizeName.NorthAmericaNumber10EnvelopeRotated] = Enums.Size.DefinedSize.NorthAmericaNumber10EnvelopeRotated,
            [PageMediaSizeName.NorthAmericaNumber9Envelope] = Enums.Size.DefinedSize.NorthAmericaNumber9Envelope,
            [PageMediaSizeName.NorthAmericaNumber11Envelope] = Enums.Size.DefinedSize.NorthAmericaNumber11Envelope,
            [PageMediaSizeName.NorthAmericaNumber12Envelope] = Enums.Size.DefinedSize.NorthAmericaNumber12Envelope,
            [PageMediaSizeName.NorthAmericaNumber14Envelope] = Enums.Size.DefinedSize.NorthAmericaNumber14Envelope,
            [PageMediaSizeName.NorthAmericaPersonalEnvelope] = Enums.Size.DefinedSize.NorthAmericaPersonalEnvelope,
            [PageMediaSizeName.NorthAmericaQuarto] = Enums.Size.DefinedSize.NorthAmericaQuarto,
            [PageMediaSizeName.NorthAmericaStatement] = Enums.Size.DefinedSize.NorthAmericaStatement,
            [PageMediaSizeName.NorthAmericaSuperA] = Enums.Size.DefinedSize.NorthAmericaSuperA,
            [PageMediaSizeName.NorthAmericaSuperB] = Enums.Size.DefinedSize.NorthAmericaSuperB,
            [PageMediaSizeName.NorthAmericaTabloid] = Enums.Size.DefinedSize.NorthAmericaTabloid,
            [PageMediaSizeName.NorthAmericaTabloidExtra] = Enums.Size.DefinedSize.NorthAmericaTabloidExtra,
            [PageMediaSizeName.OtherMetricA4Plus] = Enums.Size.DefinedSize.OtherMetricA4Plus,
            [PageMediaSizeName.OtherMetricA3Plus] = Enums.Size.DefinedSize.OtherMetricA3Plus,
            [PageMediaSizeName.OtherMetricFolio] = Enums.Size.DefinedSize.OtherMetricFolio,
            [PageMediaSizeName.OtherMetricInviteEnvelope] = Enums.Size.DefinedSize.OtherMetricInviteEnvelope,
            [PageMediaSizeName.OtherMetricItalianEnvelope] = Enums.Size.DefinedSize.OtherMetricItalianEnvelope,
            [PageMediaSizeName.PRC1Envelope] = Enums.Size.DefinedSize.PRC1Envelope,
            [PageMediaSizeName.PRC1EnvelopeRotated] = Enums.Size.DefinedSize.PRC1EnvelopeRotated,
            [PageMediaSizeName.PRC10Envelope] = Enums.Size.DefinedSize.PRC10Envelope,
            [PageMediaSizeName.PRC10EnvelopeRotated] = Enums.Size.DefinedSize.PRC10EnvelopeRotated,
            [PageMediaSizeName.PRC16K] = Enums.Size.DefinedSize.PRC16K,
            [PageMediaSizeName.PRC16KRotated] = Enums.Size.DefinedSize.PRC16KRotated,
            [PageMediaSizeName.PRC2Envelope] = Enums.Size.DefinedSize.PRC2Envelope,
            [PageMediaSizeName.PRC2EnvelopeRotated] = Enums.Size.DefinedSize.PRC2EnvelopeRotated,
            [PageMediaSizeName.PRC32K] = Enums.Size.DefinedSize.PRC32K,
            [PageMediaSizeName.PRC32KRotated] = Enums.Size.DefinedSize.PRC32KRotated,
            [PageMediaSizeName.PRC32KBig] = Enums.Size.DefinedSize.PRC32KBig,
            [PageMediaSizeName.PRC3Envelope] = Enums.Size.DefinedSize.PRC3Envelope,
            [PageMediaSizeName.PRC3EnvelopeRotated] = Enums.Size.DefinedSize.PRC3EnvelopeRotated,
            [PageMediaSizeName.PRC4Envelope] = Enums.Size.DefinedSize.PRC4Envelope,
            [PageMediaSizeName.PRC4EnvelopeRotated] = Enums.Size.DefinedSize.PRC4EnvelopeRotated,
            [PageMediaSizeName.PRC5Envelope] = Enums.Size.DefinedSize.PRC5Envelope,
            [PageMediaSizeName.PRC5EnvelopeRotated] = Enums.Size.DefinedSize.PRC5EnvelopeRotated,
            [PageMediaSizeName.PRC6Envelope] = Enums.Size.DefinedSize.PRC6Envelope,
            [PageMediaSizeName.PRC6EnvelopeRotated] = Enums.Size.DefinedSize.PRC6EnvelopeRotated,
            [PageMediaSizeName.PRC7Envelope] = Enums.Size.DefinedSize.PRC7Envelope,
            [PageMediaSizeName.PRC7EnvelopeRotated] = Enums.Size.DefinedSize.PRC7EnvelopeRotated,
            [PageMediaSizeName.PRC8Envelope] = Enums.Size.DefinedSize.PRC8Envelope,
            [PageMediaSizeName.PRC8EnvelopeRotated] = Enums.Size.DefinedSize.PRC8EnvelopeRotated,
            [PageMediaSizeName.PRC9Envelope] = Enums.Size.DefinedSize.PRC9Envelope,
            [PageMediaSizeName.PRC9EnvelopeRotated] = Enums.Size.DefinedSize.PRC9EnvelopeRotated,
            [PageMediaSizeName.Roll04Inch] = Enums.Size.DefinedSize.Roll04Inch,
            [PageMediaSizeName.Roll06Inch] = Enums.Size.DefinedSize.Roll06Inch,
            [PageMediaSizeName.Roll08Inch] = Enums.Size.DefinedSize.Roll08Inch,
            [PageMediaSizeName.Roll12Inch] = Enums.Size.DefinedSize.Roll12Inch,
            [PageMediaSizeName.Roll15Inch] = Enums.Size.DefinedSize.Roll15Inch,
            [PageMediaSizeName.Roll18Inch] = Enums.Size.DefinedSize.Roll18Inch,
            [PageMediaSizeName.Roll22Inch] = Enums.Size.DefinedSize.Roll22Inch,
            [PageMediaSizeName.Roll24Inch] = Enums.Size.DefinedSize.Roll24Inch,
            [PageMediaSizeName.Roll30Inch] = Enums.Size.DefinedSize.Roll30Inch,
            [PageMediaSizeName.Roll36Inch] = Enums.Size.DefinedSize.Roll36Inch,
            [PageMediaSizeName.Roll54Inch] = Enums.Size.DefinedSize.Roll54Inch,
            [PageMediaSizeName.JapanDoubleHagakiPostcard] = Enums.Size.DefinedSize.JapanDoubleHagakiPostcard,
            [PageMediaSizeName.JapanDoubleHagakiPostcardRotated] = Enums.Size.DefinedSize.JapanDoubleHagakiPostcardRotated,
            [PageMediaSizeName.JapanLPhoto] = Enums.Size.DefinedSize.JapanLPhoto,
            [PageMediaSizeName.Japan2LPhoto] = Enums.Size.DefinedSize.Japan2LPhoto,
            [PageMediaSizeName.JapanYou1Envelope] = Enums.Size.DefinedSize.JapanYou1Envelope,
            [PageMediaSizeName.JapanYou2Envelope] = Enums.Size.DefinedSize.JapanYou2Envelope,
            [PageMediaSizeName.JapanYou3Envelope] = Enums.Size.DefinedSize.JapanYou3Envelope,
            [PageMediaSizeName.JapanYou4EnvelopeRotated] = Enums.Size.DefinedSize.JapanYou4EnvelopeRotated,
            [PageMediaSizeName.JapanYou6Envelope] = Enums.Size.DefinedSize.JapanYou6Envelope,
            [PageMediaSizeName.JapanYou6EnvelopeRotated] = Enums.Size.DefinedSize.JapanYou6EnvelopeRotated,
            [PageMediaSizeName.NorthAmerica4x6] = Enums.Size.DefinedSize.NorthAmerica4x6,
            [PageMediaSizeName.NorthAmerica4x8] = Enums.Size.DefinedSize.NorthAmerica4x8,
            [PageMediaSizeName.NorthAmerica5x7] = Enums.Size.DefinedSize.NorthAmerica5x7,
            [PageMediaSizeName.NorthAmerica8x10] = Enums.Size.DefinedSize.NorthAmerica8x10,
            [PageMediaSizeName.NorthAmerica10x12] = Enums.Size.DefinedSize.NorthAmerica10x12,
            [PageMediaSizeName.NorthAmerica14x17] = Enums.Size.DefinedSize.NorthAmerica14x17,
            [PageMediaSizeName.BusinessCard] = Enums.Size.DefinedSize.BusinessCard,
            [PageMediaSizeName.CreditCard] = Enums.Size.DefinedSize.CreditCard
        };

        public static readonly Dictionary<string, Enums.Size.DefinedSize> XmlSizeNameMapping = new()
        {
            ["isoa0"] = Enums.Size.DefinedSize.ISOA0,
            ["isoa1"] = Enums.Size.DefinedSize.ISOA1,
            ["isoa10"] = Enums.Size.DefinedSize.ISOA10,
            ["isoa2"] = Enums.Size.DefinedSize.ISOA2,
            ["isoa3"] = Enums.Size.DefinedSize.ISOA3,
            ["isoa3extra"] = Enums.Size.DefinedSize.ISOA3Extra,
            ["isoa3rotated"] = Enums.Size.DefinedSize.ISOA3Rotated,
            ["isoa4"] = Enums.Size.DefinedSize.ISOA4,
            ["isoa4extra"] = Enums.Size.DefinedSize.ISOA4Extra,
            ["isoa4rotated"] = Enums.Size.DefinedSize.ISOA4Rotated,
            ["isoa5"] = Enums.Size.DefinedSize.ISOA5,
            ["isoa5extra"] = Enums.Size.DefinedSize.ISOA5Extra,
            ["isoa5rotated"] = Enums.Size.DefinedSize.ISOA5Rotated,
            ["isoa6"] = Enums.Size.DefinedSize.ISOA6,
            ["isoa6rotated"] = Enums.Size.DefinedSize.ISOA6Rotated,
            ["isoa7"] = Enums.Size.DefinedSize.ISOA7,
            ["isoa8"] = Enums.Size.DefinedSize.ISOA8,
            ["isoa9"] = Enums.Size.DefinedSize.ISOA9,
            ["isob0"] = Enums.Size.DefinedSize.ISOB0,
            ["isob1"] = Enums.Size.DefinedSize.ISOB1,
            ["isob10"] = Enums.Size.DefinedSize.ISOB10,
            ["isob2"] = Enums.Size.DefinedSize.ISOB2,
            ["isob3"] = Enums.Size.DefinedSize.ISOB3,
            ["isob4"] = Enums.Size.DefinedSize.ISOB4,
            ["isob4envelope"] = Enums.Size.DefinedSize.ISOB4Envelope,
            ["isob5envelope"] = Enums.Size.DefinedSize.ISOB5Envelope,
            ["isob5extra"] = Enums.Size.DefinedSize.ISOB5Extra,
            ["isob7"] = Enums.Size.DefinedSize.ISOB7,
            ["isob8"] = Enums.Size.DefinedSize.ISOB8,
            ["isob9"] = Enums.Size.DefinedSize.ISOB9,
            ["isoc0"] = Enums.Size.DefinedSize.ISOC0,
            ["isoc1"] = Enums.Size.DefinedSize.ISOC1,
            ["isoc2"] = Enums.Size.DefinedSize.ISOC2,
            ["isoc3"] = Enums.Size.DefinedSize.ISOC3,
            ["isoc3envelope"] = Enums.Size.DefinedSize.ISOC3Envelope,
            ["isoc4"] = Enums.Size.DefinedSize.ISOC4,
            ["isoc4envelope"] = Enums.Size.DefinedSize.ISOC4Envelope,
            ["isoc5"] = Enums.Size.DefinedSize.ISOC5,
            ["isoc5envelope"] = Enums.Size.DefinedSize.ISOC5Envelope,
            ["isoc6"] = Enums.Size.DefinedSize.ISOC6,
            ["isoc6c5envelope"] = Enums.Size.DefinedSize.ISOC6C5Envelope,
            ["isoc6envelope"] = Enums.Size.DefinedSize.ISOC6Envelope,
            ["isoc7"] = Enums.Size.DefinedSize.ISOC7,
            ["isoc8"] = Enums.Size.DefinedSize.ISOC8,
            ["isoc9"] = Enums.Size.DefinedSize.ISOC9,
            ["isoc10"] = Enums.Size.DefinedSize.ISOC10,
            ["isodlenvelope"] = Enums.Size.DefinedSize.ISODLEnvelope,
            ["isodlenveloperotated"] = Enums.Size.DefinedSize.ISODLEnvelopeRotated,
            ["isosra3"] = Enums.Size.DefinedSize.ISOSRA3,
            ["japanquadruplehagakipostcard"] = Enums.Size.DefinedSize.JapanQuadrupleHagakiPostcard,
            ["jisb0"] = Enums.Size.DefinedSize.JISB0,
            ["jisb1"] = Enums.Size.DefinedSize.JISB1,
            ["jisb10"] = Enums.Size.DefinedSize.JISB10,
            ["jisb2"] = Enums.Size.DefinedSize.JISB2,
            ["jisb3"] = Enums.Size.DefinedSize.JISB3,
            ["jisb4"] = Enums.Size.DefinedSize.JISB4,
            ["jisb4rotated"] = Enums.Size.DefinedSize.JISB4Rotated,
            ["jisb5"] = Enums.Size.DefinedSize.JISB5,
            ["jisb5rotated"] = Enums.Size.DefinedSize.JISB5Rotated,
            ["jisb6"] = Enums.Size.DefinedSize.JISB6,
            ["jisb6rotated"] = Enums.Size.DefinedSize.JISB6Rotated,
            ["jisb7"] = Enums.Size.DefinedSize.JISB7,
            ["jisb8"] = Enums.Size.DefinedSize.JISB8,
            ["jisb9"] = Enums.Size.DefinedSize.JISB9,
            ["japanchou3envelope"] = Enums.Size.DefinedSize.JapanChou3Envelope,
            ["japanchou3enveloperotated"] = Enums.Size.DefinedSize.JapanChou3EnvelopeRotated,
            ["japanchou4envelope"] = Enums.Size.DefinedSize.JapanChou4Envelope,
            ["japanchou4enveloperotated"] = Enums.Size.DefinedSize.JapanChou4EnvelopeRotated,
            ["japanhagakipostcard"] = Enums.Size.DefinedSize.JapanHagakiPostcard,
            ["japanhagakipostcardrotated"] = Enums.Size.DefinedSize.JapanHagakiPostcardRotated,
            ["japankaku2envelope"] = Enums.Size.DefinedSize.JapanKaku2Envelope,
            ["japankaku2enveloperotated"] = Enums.Size.DefinedSize.JapanKaku2EnvelopeRotated,
            ["japankaku3envelope"] = Enums.Size.DefinedSize.JapanKaku3Envelope,
            ["japankaku3enveloperotated"] = Enums.Size.DefinedSize.JapanKaku3EnvelopeRotated,
            ["japanyou4envelope"] = Enums.Size.DefinedSize.JapanYou4Envelope,
            ["northamerica10x11"] = Enums.Size.DefinedSize.NorthAmerica10x11,
            ["northamerica10x14"] = Enums.Size.DefinedSize.NorthAmerica10x14,
            ["northamerica11x17"] = Enums.Size.DefinedSize.NorthAmerica11x17,
            ["northamerica9x11"] = Enums.Size.DefinedSize.NorthAmerica9x11,
            ["northamericaarchitectureasheet"] = Enums.Size.DefinedSize.NorthAmericaArchitectureASheet,
            ["northamericaarchitecturebsheet"] = Enums.Size.DefinedSize.NorthAmericaArchitectureBSheet,
            ["northamericaarchitecturecsheet"] = Enums.Size.DefinedSize.NorthAmericaArchitectureCSheet,
            ["northamericaarchitecturedsheet"] = Enums.Size.DefinedSize.NorthAmericaArchitectureDSheet,
            ["northamericaarchitectureesheet"] = Enums.Size.DefinedSize.NorthAmericaArchitectureESheet,
            ["northamericacsheet"] = Enums.Size.DefinedSize.NorthAmericaCSheet,
            ["northamericadsheet"] = Enums.Size.DefinedSize.NorthAmericaDSheet,
            ["northamericaesheet"] = Enums.Size.DefinedSize.NorthAmericaESheet,
            ["northamericaexecutive"] = Enums.Size.DefinedSize.NorthAmericaExecutive,
            ["northamericagermanlegalfanfold"] = Enums.Size.DefinedSize.NorthAmericaGermanLegalFanfold,
            ["northamericagermanstandardfanfold"] = Enums.Size.DefinedSize.NorthAmericaGermanStandardFanfold,
            ["northamericalegal"] = Enums.Size.DefinedSize.NorthAmericaLegal,
            ["northamericalegalextra"] = Enums.Size.DefinedSize.NorthAmericaLegalExtra,
            ["northamericaletter"] = Enums.Size.DefinedSize.NorthAmericaLetter,
            ["northamericaletterextra"] = Enums.Size.DefinedSize.NorthAmericaLetterExtra,
            ["northamericaletterplus"] = Enums.Size.DefinedSize.NorthAmericaLetterPlus,
            ["northamericaletterrotated"] = Enums.Size.DefinedSize.NorthAmericaLetterRotated,
            ["northamericamonarchenvelope"] = Enums.Size.DefinedSize.NorthAmericaMonarchEnvelope,
            ["northamericanote"] = Enums.Size.DefinedSize.NorthAmericaNote,
            ["northamericanumber10envelope"] = Enums.Size.DefinedSize.NorthAmericaNumber10Envelope,
            ["northamericanumber10enveloperotated"] = Enums.Size.DefinedSize.NorthAmericaNumber10EnvelopeRotated,
            ["northamericanumber11envelope"] = Enums.Size.DefinedSize.NorthAmericaNumber11Envelope,
            ["northamericanumber12envelope"] = Enums.Size.DefinedSize.NorthAmericaNumber12Envelope,
            ["northamericanumber14envelope"] = Enums.Size.DefinedSize.NorthAmericaNumber14Envelope,
            ["northamericanumber9envelope"] = Enums.Size.DefinedSize.NorthAmericaNumber9Envelope,
            ["northamericapersonalenvelope"] = Enums.Size.DefinedSize.NorthAmericaPersonalEnvelope,
            ["northamericaquarto"] = Enums.Size.DefinedSize.NorthAmericaQuarto,
            ["northamericastatement"] = Enums.Size.DefinedSize.NorthAmericaStatement,
            ["northamericasupera"] = Enums.Size.DefinedSize.NorthAmericaSuperA,
            ["northamericasuperb"] = Enums.Size.DefinedSize.NorthAmericaSuperB,
            ["northamericatabloid"] = Enums.Size.DefinedSize.NorthAmericaTabloid,
            ["northamericatabloidextra"] = Enums.Size.DefinedSize.NorthAmericaTabloidExtra,
            ["othermetrica3plus"] = Enums.Size.DefinedSize.OtherMetricA3Plus,
            ["othermetrica4plus"] = Enums.Size.DefinedSize.OtherMetricA4Plus,
            ["othermetricfolio"] = Enums.Size.DefinedSize.OtherMetricFolio,
            ["othermetricinviteenvelope"] = Enums.Size.DefinedSize.OtherMetricInviteEnvelope,
            ["othermetricitalianenvelope"] = Enums.Size.DefinedSize.OtherMetricItalianEnvelope,
            ["japan2lphoto"] = Enums.Size.DefinedSize.Japan2LPhoto,
            ["japandoublehagakipostcard"] = Enums.Size.DefinedSize.JapanDoubleHagakiPostcard,
            ["japandoublehagakipostcardrotated"] = Enums.Size.DefinedSize.JapanDoubleHagakiPostcardRotated,
            ["japanlphoto"] = Enums.Size.DefinedSize.JapanLPhoto,
            ["japanyou1envelope"] = Enums.Size.DefinedSize.JapanYou1Envelope,
            ["japanyou2envelope"] = Enums.Size.DefinedSize.JapanYou2Envelope,
            ["japanyou3envelope"] = Enums.Size.DefinedSize.JapanYou3Envelope,
            ["japanyou4enveloperotated"] = Enums.Size.DefinedSize.JapanYou4EnvelopeRotated,
            ["japanyou6envelope"] = Enums.Size.DefinedSize.JapanYou6Envelope,
            ["japanyou6enveloperotated"] = Enums.Size.DefinedSize.JapanYou6EnvelopeRotated,
            ["northamerica10x12"] = Enums.Size.DefinedSize.NorthAmerica10x12,
            ["northamerica14x17"] = Enums.Size.DefinedSize.NorthAmerica14x17,
            ["northamerica4x6"] = Enums.Size.DefinedSize.NorthAmerica4x6,
            ["northamerica4x8"] = Enums.Size.DefinedSize.NorthAmerica4x8,
            ["northamerica5x7"] = Enums.Size.DefinedSize.NorthAmerica5x7,
            ["northamerica8x10"] = Enums.Size.DefinedSize.NorthAmerica8x10,
            ["prc1envelope"] = Enums.Size.DefinedSize.PRC1Envelope,
            ["prc1enveloperotated"] = Enums.Size.DefinedSize.PRC1EnvelopeRotated,
            ["prc10envelope"] = Enums.Size.DefinedSize.PRC10Envelope,
            ["prc10enveloperotated"] = Enums.Size.DefinedSize.PRC10EnvelopeRotated,
            ["prc16k"] = Enums.Size.DefinedSize.PRC16K,
            ["prc16krotated"] = Enums.Size.DefinedSize.PRC16KRotated,
            ["prc2envelope"] = Enums.Size.DefinedSize.PRC2Envelope,
            ["prc2enveloperotated"] = Enums.Size.DefinedSize.PRC2EnvelopeRotated,
            ["prc32k"] = Enums.Size.DefinedSize.PRC32K,
            ["prc32kbig"] = Enums.Size.DefinedSize.PRC32KBig,
            ["prc32krotated"] = Enums.Size.DefinedSize.PRC32KRotated,
            ["prc3envelope"] = Enums.Size.DefinedSize.PRC3Envelope,
            ["prc3enveloperotated"] = Enums.Size.DefinedSize.PRC3EnvelopeRotated,
            ["prc4envelope"] = Enums.Size.DefinedSize.PRC4Envelope,
            ["prc4enveloperotated"] = Enums.Size.DefinedSize.PRC4EnvelopeRotated,
            ["prc5envelope"] = Enums.Size.DefinedSize.PRC5Envelope,
            ["prc5enveloperotated"] = Enums.Size.DefinedSize.PRC5EnvelopeRotated,
            ["prc6envelope"] = Enums.Size.DefinedSize.PRC6Envelope,
            ["prc6enveloperotated"] = Enums.Size.DefinedSize.PRC6EnvelopeRotated,
            ["prc7envelope"] = Enums.Size.DefinedSize.PRC7Envelope,
            ["prc7enveloperotated"] = Enums.Size.DefinedSize.PRC7EnvelopeRotated,
            ["prc8envelope"] = Enums.Size.DefinedSize.PRC8Envelope,
            ["prc8enveloperotated"] = Enums.Size.DefinedSize.PRC8EnvelopeRotated,
            ["prc9envelope"] = Enums.Size.DefinedSize.PRC9Envelope,
            ["prc9enveloperotated"] = Enums.Size.DefinedSize.PRC9EnvelopeRotated,
            ["roll04inch"] = Enums.Size.DefinedSize.Roll04Inch,
            ["roll06inch"] = Enums.Size.DefinedSize.Roll06Inch,
            ["roll08inch"] = Enums.Size.DefinedSize.Roll08Inch,
            ["roll12inch"] = Enums.Size.DefinedSize.Roll12Inch,
            ["roll15inch"] = Enums.Size.DefinedSize.Roll15Inch,
            ["roll18inch"] = Enums.Size.DefinedSize.Roll18Inch,
            ["roll22inch"] = Enums.Size.DefinedSize.Roll22Inch,
            ["roll24inch"] = Enums.Size.DefinedSize.Roll24Inch,
            ["roll30inch"] = Enums.Size.DefinedSize.Roll30Inch,
            ["roll36inch"] = Enums.Size.DefinedSize.Roll36Inch,
            ["roll54inch"] = Enums.Size.DefinedSize.Roll54Inch,
            ["businesscard"] = Enums.Size.DefinedSize.BusinessCard,
            ["creditcard"] = Enums.Size.DefinedSize.CreditCard
        };

        public static readonly Dictionary<OutputColor, Enums.Color> ColorMapping = new()
        {
            [OutputColor.Color] = Enums.Color.Color,
            [OutputColor.Grayscale] = Enums.Color.Grayscale,
            [OutputColor.Monochrome] = Enums.Color.Monochrome
        };

        public static readonly Dictionary<OutputQuality, Enums.Quality> QualityMapping = new()
        {
            [OutputQuality.Automatic] = Enums.Quality.Automatic,
            [OutputQuality.Draft] = Enums.Quality.Draft,
            [OutputQuality.Fax] = Enums.Quality.Fax,
            [OutputQuality.High] = Enums.Quality.High,
            [OutputQuality.Normal] = Enums.Quality.Normal,
            [OutputQuality.Photographic] = Enums.Quality.Photographic,
            [OutputQuality.Text] = Enums.Quality.Text
        };

        public static readonly Dictionary<Duplexing, Enums.DoubleSided> DoubleSidedMapping = new()
        {
            [Duplexing.OneSided] = Enums.DoubleSided.OneSided,
            [Duplexing.TwoSidedShortEdge] = Enums.DoubleSided.DoubleSidedShortEdge,
            [Duplexing.TwoSidedLongEdge] = Enums.DoubleSided.DoubleSidedLongEdge
        };

        public static readonly Dictionary<PageMediaType, Enums.Type> TypeMapping = new()
        {
            [PageMediaType.AutoSelect] = Enums.Type.AutoSelect,
            [PageMediaType.Archival] = Enums.Type.Archival,
            [PageMediaType.BackPrintFilm] = Enums.Type.BackPrintFilm,
            [PageMediaType.Bond] = Enums.Type.Bond,
            [PageMediaType.CardStock] = Enums.Type.CardStock,
            [PageMediaType.Continuous] = Enums.Type.Continuous,
            [PageMediaType.EnvelopePlain] = Enums.Type.EnvelopePlain,
            [PageMediaType.EnvelopeWindow] = Enums.Type.EnvelopeWindow,
            [PageMediaType.Fabric] = Enums.Type.Fabric,
            [PageMediaType.HighResolution] = Enums.Type.HighResolution,
            [PageMediaType.Label] = Enums.Type.Label,
            [PageMediaType.MultiLayerForm] = Enums.Type.MultiLayerForm,
            [PageMediaType.MultiPartForm] = Enums.Type.MultiPartForm,
            [PageMediaType.Photographic] = Enums.Type.Photographic,
            [PageMediaType.PhotographicFilm] = Enums.Type.PhotographicFilm,
            [PageMediaType.PhotographicGlossy] = Enums.Type.PhotographicGlossy,
            [PageMediaType.PhotographicHighGloss] = Enums.Type.PhotographicHighGloss,
            [PageMediaType.PhotographicMatte] = Enums.Type.PhotographicMatte,
            [PageMediaType.PhotographicSatin] = Enums.Type.PhotographicSatin,
            [PageMediaType.PhotographicSemiGloss] = Enums.Type.PhotographicSemiGloss,
            [PageMediaType.Plain] = Enums.Type.Plain,
            [PageMediaType.Screen] = Enums.Type.Screen,
            [PageMediaType.ScreenPaged] = Enums.Type.ScreenPaged,
            [PageMediaType.Stationery] = Enums.Type.Stationery,
            [PageMediaType.TabStockFull] = Enums.Type.TabStockFull,
            [PageMediaType.TabStockPreCut] = Enums.Type.TabStockPreCut,
            [PageMediaType.Transparency] = Enums.Type.Transparency,
            [PageMediaType.TShirtTransfer] = Enums.Type.TShirtTransfer
        };

        public static readonly Dictionary<InputBin, Enums.Source> SourceMapping = new()
        {
            [InputBin.AutoSelect] = Enums.Source.AutoSelect,
            [InputBin.Cassette] = Enums.Source.Cassette,
            [InputBin.Tractor] = Enums.Source.Tractor,
            [InputBin.AutoSheetFeeder] = Enums.Source.AutoSheetFeeder,
            [InputBin.Manual] = Enums.Source.Manual
        };
    }
}